// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RegistrationApp4;
using System;

namespace RegistrationApp4.Migrations
{
    [DbContext(typeof(RegAppDBContext))]
    [Migration("20170918154100_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegistrationApp4.Courses", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID");

                    b.Property<string>("CourseName")
                        .HasColumnType("nchar(100)");

                    b.Property<int?>("CreditHours");

                    b.Property<string>("Dwstring")
                        .HasColumnName("DWstring")
                        .HasColumnType("nchar(5)");

                    b.Property<string>("EndTime")
                        .HasColumnType("nchar(7)");

                    b.Property<int?>("InstructorId")
                        .HasColumnName("InstructorID");

                    b.Property<int?>("SpotsAvail");

                    b.Property<string>("StartTime")
                        .HasColumnType("nchar(7)");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("nchar(8)");

                    b.Property<int?>("TotalSpots");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("RegistrationApp4.Instructors", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID");

                    b.Property<string>("Fname")
                        .HasColumnType("nchar(30)");

                    b.Property<string>("Lname")
                        .HasColumnType("nchar(30)");

                    b.Property<int?>("NumClasses");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("RegistrationApp4.Students", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID");

                    b.Property<string>("Classification")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("Fname")
                        .HasColumnType("nchar(30)");

                    b.Property<string>("Lname")
                        .HasColumnType("nchar(30)");

                    b.Property<string>("Major")
                        .HasColumnType("nchar(100)");

                    b.Property<int?>("NumClasses");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
